baseURL = "https://yu0035.github.io/"
languageCode = "ja-jp"
title = "マイクラ日記"
theme = "m10c"

[params]
    avatar = "avatar2.jpg"
    description = "マイクラのModを作成したり、ラキューやレゴでマイクラアイテムを作ったりしています！"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true